/* Generated by 'Generate-Swift-Storyboard-Constants.py' DO NOT CHANGE */

import Foundation

struct Constants {

	struct Segue {
		static let ToSecondViewController = "ToSecondViewController"
	}

	struct ViewController {
		static let First = "First"
		static let Second = "Second"
	}

	struct ReuseCell {
		static let ExampleCell = "ExampleCell"
	}

}