/* Generated by 'Generate-Swift-Storyboard-Constants.py' DO NOT CHANGE */

import UIKit

enum StoryboardSegue: String
{
	case ToSecondViewController = "ToSecondViewController"
}

enum StoryboardViewController: String
{
	case First = "First"
	case Second = "Second"

	func instantiate() -> UIViewController?
	{
		let storyboard = UIStoryboard(name: "Main", bundle: nil)
		
		return storyboard.instantiateViewControllerWithIdentifier(self.rawValue)
	}
}

enum StoryboardReuseCell: String
{
	case ExampleCell = "ExampleCell"
}

extension UIViewController
{
	func performSegue(segue: StoryboardSegue, sender: AnyObject? = nil)
	{
		self.performSegueWithIdentifier(segue.rawValue, sender: sender)	}
}
